{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.voqal",
    "module": "voqal-sdk",
    "version": "1.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "voqal-sdk-1.2.8.aar",
          "url": "voqal-sdk-1.2.8.aar",
          "size": 584467,
          "sha512": "eb2161a5e850bc582eed11ac15def910d03bcc57d5a27d44a044994ffc2addc17ecbcb976ee2de764e6baac2276e660c0d801430f9eae1d980d2e8412a0af971",
          "sha256": "8f2e291e9c067b8a8036390a37210af184d8a70def88fe7b6dfe2d7bd1b42e68",
          "sha1": "9256b1a52f1760c8ea8a7f409c4dda0c67b134fb",
          "md5": "11aad84136916fe9a7e4d95123b71c3d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "voqal-sdk-1.2.8.aar",
          "url": "voqal-sdk-1.2.8.aar",
          "size": 584467,
          "sha512": "eb2161a5e850bc582eed11ac15def910d03bcc57d5a27d44a044994ffc2addc17ecbcb976ee2de764e6baac2276e660c0d801430f9eae1d980d2e8412a0af971",
          "sha256": "8f2e291e9c067b8a8036390a37210af184d8a70def88fe7b6dfe2d7bd1b42e68",
          "sha1": "9256b1a52f1760c8ea8a7f409c4dda0c67b134fb",
          "md5": "11aad84136916fe9a7e4d95123b71c3d"
        }
      ]
    }
  ]
}
