{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.voqal",
    "module": "voqal-sdk",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "voqal-sdk-1.5.2.aar",
          "url": "voqal-sdk-1.5.2.aar",
          "size": 644750,
          "sha512": "4239d0f5684e93585bab4eed16041bc50cc2b3c95ff90d2931255dda4fa33bc31e4e47ebc1594c0af7e6d99fbf6becd28a6025aa938623c302669c5f0a9dc4c3",
          "sha256": "5e0fb9141d3b514c917006d7cae59505d1e4738261f7937cd2465735983419b9",
          "sha1": "55cca71c6a8d1ec04c5316f1ca56d3f47430aa10",
          "md5": "b8878869cbbae0c4bb12b4bae0bad140"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "voqal-sdk-1.5.2.aar",
          "url": "voqal-sdk-1.5.2.aar",
          "size": 644750,
          "sha512": "4239d0f5684e93585bab4eed16041bc50cc2b3c95ff90d2931255dda4fa33bc31e4e47ebc1594c0af7e6d99fbf6becd28a6025aa938623c302669c5f0a9dc4c3",
          "sha256": "5e0fb9141d3b514c917006d7cae59505d1e4738261f7937cd2465735983419b9",
          "sha1": "55cca71c6a8d1ec04c5316f1ca56d3f47430aa10",
          "md5": "b8878869cbbae0c4bb12b4bae0bad140"
        }
      ]
    }
  ]
}
