{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.voqal",
    "module": "voqal-sdk-rabbit",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "voqal-sdk-rabbit-1.5.1.aar",
          "url": "voqal-sdk-rabbit-1.5.1.aar",
          "size": 1011026,
          "sha512": "c83a4b820dbdd5a68e9f9193271c3b7e11bb2542cb55f681348b1c743f5e34a60580d66d8542220fbd9f26839d18c5ad6d3932c5ece8170fa2516ac0963f4c01",
          "sha256": "ada1e36be3f4d673506588596ceae3dde58a105ae8a1f3c32bf5896453cdcef2",
          "sha1": "f2650aa56a3a46539a2d6f330366b5b4c2d548eb",
          "md5": "2de4132fdd8272e1cf9ea4bf3e2edb3f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "voqal-sdk-rabbit-1.5.1.aar",
          "url": "voqal-sdk-rabbit-1.5.1.aar",
          "size": 1011026,
          "sha512": "c83a4b820dbdd5a68e9f9193271c3b7e11bb2542cb55f681348b1c743f5e34a60580d66d8542220fbd9f26839d18c5ad6d3932c5ece8170fa2516ac0963f4c01",
          "sha256": "ada1e36be3f4d673506588596ceae3dde58a105ae8a1f3c32bf5896453cdcef2",
          "sha1": "f2650aa56a3a46539a2d6f330366b5b4c2d548eb",
          "md5": "2de4132fdd8272e1cf9ea4bf3e2edb3f"
        }
      ]
    }
  ]
}
