{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.voqal",
    "module": "voqal-sdk",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "voqal-sdk-1.2.7.aar",
          "url": "voqal-sdk-1.2.7.aar",
          "size": 580437,
          "sha512": "c6452227664515f4b4f84df0e977b41542768ecb1f3f713cf72ac07342e264f9226fe51b0086d657b449440ea3fdb072682d03f6ea6c8e83e58708279b739227",
          "sha256": "c8b215f274faf7fca12a54a66d6b7969f81f5bc76388da9f5d5a54b8f56e8f3b",
          "sha1": "974f7240239c99218058b4548df4fb8266ca9182",
          "md5": "ceb5d0dd94911799a95a886f4f844fdf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "voqal-sdk-1.2.7.aar",
          "url": "voqal-sdk-1.2.7.aar",
          "size": 580437,
          "sha512": "c6452227664515f4b4f84df0e977b41542768ecb1f3f713cf72ac07342e264f9226fe51b0086d657b449440ea3fdb072682d03f6ea6c8e83e58708279b739227",
          "sha256": "c8b215f274faf7fca12a54a66d6b7969f81f5bc76388da9f5d5a54b8f56e8f3b",
          "sha1": "974f7240239c99218058b4548df4fb8266ca9182",
          "md5": "ceb5d0dd94911799a95a886f4f844fdf"
        }
      ]
    }
  ]
}
