{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.voqal",
    "module": "voqal-sdk",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "voqal-sdk-1.2.7.aar",
          "url": "voqal-sdk-1.2.7.aar",
          "size": 580117,
          "sha512": "099305e978eb1a075bc49404271986bf70940e1b4fa3709ea394e6c8ed1eceacfeef6ab379b93cb015c31b821fd76fa43d480506c0993c9709d8e962689c6014",
          "sha256": "6489e5f4d5d7624326c1e8302ecb4afb369f552d5a1fff437fe0107c30416a78",
          "sha1": "740206762ee961fed597a1adda64a92937c8e443",
          "md5": "7c7e79444f5109c645bc143bf3fdf9e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "voqal-sdk-1.2.7.aar",
          "url": "voqal-sdk-1.2.7.aar",
          "size": 580117,
          "sha512": "099305e978eb1a075bc49404271986bf70940e1b4fa3709ea394e6c8ed1eceacfeef6ab379b93cb015c31b821fd76fa43d480506c0993c9709d8e962689c6014",
          "sha256": "6489e5f4d5d7624326c1e8302ecb4afb369f552d5a1fff437fe0107c30416a78",
          "sha1": "740206762ee961fed597a1adda64a92937c8e443",
          "md5": "7c7e79444f5109c645bc143bf3fdf9e5"
        }
      ]
    }
  ]
}
